<a href="https://colab.research.google.com/github/junzer0/Neural-Network/blob/main/Perceptron_AND_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Perceptron AND operator

![alt text](https://drive.google.com/uc?id=1EVKYuVhLOMcvCOo4x2WDe9-rzbsIqe47)



## Inputs, outputs and weights

In [1]:
import numpy as np

In [2]:
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [3]:
inputs.shape

(4, 2)

In [4]:
outputs = np.array([0, 0, 0, 1])

In [5]:
outputs.shape

(4,)

In [6]:
weights = np.array([0.0, 0.0])

In [7]:
learning_rate = 0.1

## Step function

In [8]:
def step_function(sum):
  if (sum >= 1):
    return 1
  return 0

## Calculate output

In [9]:
def calculate_output(instance):
  s = instance.dot(weights)
  return step_function(s)

In [10]:
calculate_output(np.array([[1,1]]))

0

## Train

In [11]:
len(outputs)

4

In [12]:
inputs[3]

array([1, 1])

In [13]:
0 - 1

-1

In [14]:
abs(0 - 1)

1

In [15]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [16]:
inputs[1]

array([0, 1])

In [17]:
inputs[1][0]

0

In [18]:
inputs[1][1]

1

In [19]:
def train():
  total_error = 1
  while (total_error != 0):
    total_error = 0
    for i in range(len(outputs)):
      prediction = calculate_output(inputs[i])
      error = abs(outputs[i] - prediction)
      total_error += error
      if error > 0:
        for j in range(len(weights)):
          weights[j] = weights[j] + (learning_rate * inputs[i][j] * error)
          print('Weight updated: ' + str(weights[j]))
    print('Total error: ' + str(total_error))

In [20]:
train()

Weight updated: 0.1
Weight updated: 0.1
Total error: 1
Weight updated: 0.2
Weight updated: 0.2
Total error: 1
Weight updated: 0.30000000000000004
Weight updated: 0.30000000000000004
Total error: 1
Weight updated: 0.4
Weight updated: 0.4
Total error: 1
Weight updated: 0.5
Weight updated: 0.5
Total error: 1
Total error: 0


## Classification

In [21]:
weights

array([0.5, 0.5])

In [22]:
calculate_output(np.array([0,0]))

0

In [23]:
calculate_output(np.array([0,1]))

0

In [24]:
calculate_output(np.array([1,0]))

0

In [25]:
calculate_output(np.array([1,1]))

1